import{a as q,S as E,i as n}from"./assets/vendor-DSl0TciY.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const A="19917626-ad117b4262bded0ead70af2db",B="https://pixabay.com/api/",g=15;async function y(e,r=1){if(!e||typeof e!="string")throw new Error("Query must be a non-empty string");const i={key:A,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:g,page:r};return(await q.get(B,{params:i})).data}const p=document.querySelector(".gallery"),b=document.querySelector(".loader"),u=document.querySelector(".load-more"),w=new E(".gallery a",{captionDelay:250});function L(e){const r=e.map(({webformatURL:i,largeImageURL:s,tags:t,likes:o,views:a,comments:v,downloads:R})=>`
      <li class="gallery-item">
        <a href="${s}">
          <img src="${i}" alt="${t}" loading="lazy" />
        </a>
        <ul class="info">
          <li><b>Likes:</b> ${o}</li>
          <li><b>Views:</b> ${a}</li>
          <li><b>Comments:</b> ${v}</li>
          <li><b>Downloads:</b> ${R}</li>
        </ul>
      </li>`).join("");p.insertAdjacentHTML("beforeend",r),w.refresh()}function $(){p.innerHTML="",w.refresh()}function S(){b.hidden=!1}function P(){b.hidden=!0}function h(){u&&(u.hidden=!1)}function l(){u&&(u.hidden=!0)}const M=document.querySelector(".form"),O=document.querySelector('input[name="search-text"]'),f=document.querySelector(".load-more");let c="",d=1,m=0;M.addEventListener("submit",async e=>{if(e.preventDefault(),c=O.value.trim(),!c){n.warning({message:"Please enter a search term!",position:"topRight"});return}$(),l(),S(),d=1;try{const r=await y(c,d);if(m=r.totalHits,!r.hits.length){n.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}L(r.hits),m<=g?(l(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):h()}catch(r){console.error(r),n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{P()}});f.addEventListener("click",async()=>{l(),f.disabled=!0,S(),d+=1;try{const e=await y(c,d);Array.isArray(e.hits)&&e.hits.length>0?(L(e.hits),x(),document.querySelectorAll(".gallery-item").length>=m?(l(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):h()):(n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),l())}catch(e){console.error(e),n.error({title:"Error",message:"Something went wrong while loading more images.",position:"topRight"}),h()}finally{P(),f.disabled=!1}});function x(){const e=document.querySelector(".gallery-item");if(!e)return;const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
