import{a as P,S as q,i as s}from"./assets/vendor-DSl0TciY.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const v="19917626-ad117b4262bded0ead70af2db",B="https://pixabay.com/api/",E=15;async function d(o,t=1){if(!o||typeof o!="string")throw new Error("Query must be a non-empty string");const n={key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:E,page:t};return(await P.get(B,{params:n})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more"),g=new q(".gallery a",{captionDelay:250});function y(o){const t=o.map(({webformatURL:n,largeImageURL:i,tags:e,likes:r,views:a,comments:L,downloads:S})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${n}" alt="${e}" loading="lazy" />
        </a>
        <ul class="info">
          <li><b>Likes:</b> ${r}</li>
          <li><b>Views:</b> ${a}</li>
          <li><b>Comments:</b> ${L}</li>
          <li><b>Downloads:</b> ${S}</li>
        </ul>
      </li>`).join("");f.insertAdjacentHTML("beforeend",t),g.refresh()}function R(){f.innerHTML="",g.refresh()}function p(){m.hidden=!1}function b(){m.hidden=!0}function $(){h.hidden=!1}function w(){h.hidden=!0}const M=document.querySelector(".form"),A=document.querySelector('input[name="search-text"]'),O=document.querySelector(".load-more");let l="",c=1,u=0;M.addEventListener("submit",async o=>{if(o.preventDefault(),l=A.value.trim(),!l){s.warning({message:"Please enter a search term!",position:"topRight"});return}R(),w(),p(),c=1;try{const t=await d(l,c);if(u=t.totalHits,!t.hits.length){s.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(t.hits),t.hits.length<u&&$()}catch{s.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{b()}});O.addEventListener("click",async()=>{c++,p();try{const o=await d(l,c);y(o.hits),x(),document.querySelectorAll(".gallery-item").length>=u&&(w(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{s.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{b()}});function x(){const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
